### ISSUE TITLE
Question about being hacked

### ISSUE THREAD

**Issue by ScottyProw** [erikjjohnson/pwdsafe-iphone#3]
Many of the passwords for accounts I store in PasswordSafes were hacked.  I'm changing them all, but because my iPhone this week also prompted me to change my passcode, I'm paranoid that spyware is monitoring everything I do on my phone.  I changed the passwords for all the Safes I use in your PasswordSafes app, but if someone were monitoring my phone, they'd be able to see my new password, I would think. Can you shed any light whether this kind of spying is possible...or, recommendations for how better to protect myself other than what I've already done?  Thank you!

**Comment by erikjjohnson** [comment]
Hi ScottyProw, sorry to hear about your troubles.  There are a few things I could do with the app, and, depending on what you are doing, a few things you could do to.  But first, a disclaimer: I'm a practical person when it comes to security. I pay attention to security, but I try not to be paranoid about security.  If you are looking for extremes of what you can do, I'm not the right person to ask.

Anyway, a few simple things you can do, and then a set of things I should look into.

* For each individual password you store in a safe, use the random password generator in the app to use different passwords for every account.  It is the little "shuffle" icon next to the password field in the app.  You can also go into the Settings -> PasswordSafes and increase the length of these randomly generated passwords.  Basically, don't use the same password, or similar passwords anywhere, the longer and more (pseudo)random the better.

* For the passphrase to a safe, make it a sentence, not a "password".  I know these long passphrases are a pain to type on a phone but they tend to find a nice balance between what a human can remember and security.

* For sites that offer something called two-factor authentication, opt-in and use it.  If you have never tried this before what happens is that your account gets both a password (that you can store in a safe) and a sort of "PIN" that changes every 30 seconds or so (called a one-time password, OTP).  To know what your OTP is you would use another app, like Google Authenticator, that will tell you OTP.  With this system, if someone steals your password, they won't likely also have stolen the OTP. If someone happens to steal both your password and OTP, the OTP will only be valid for 30 seconds and so likely won't get used in time by the hacker.   Google accounts (gmail, etc) have two-factor auth, as do, I believe, Amazon, and many financial institutions are adding/have added it.


For me and this app, it is certainly possible that my code or the encryption code I used from the PasswordSafe project has bugs or needs updating.  I don't have any indication that this is true, but it is always possible with me and with software. There is now, I believe, a way for me to integrate the password for each safe with Apple's TouchID so that the main password for each safe could be tied in with your fingerprint.  I don't know if that would make the situation better or worse - if the hack you experienced was inside of your phone or inside of iOS, then this might not help, but at least if I integrated with TouchID you have all of Apple looking at the security of TouchID.

For my part, again, I'm sorry about what happened.  I have not updated the app in while mostly because I didn't know if anyone was still using it other than me. :)  If you are still using it after all of this, let me know as it will help to keep me motivated to update it.

**Comment by ScottyProw** [comment]
Thanks very much for replying so quickly - and with such great tips, Erik.

I apologize for taking so long to write back.

My fear about a hacker monitoring my phone in real-time as I typed
passwords to open each safe was unfounded apparently.  After updating all
my passwords - both for the app's safes and my individual sites/services,
the problem of someone gaining access to my various accounts and making
changes has stopped.  No money was stolen from me.

Yay!

Thanks again,

Great app.  Hope you continue to support it.

Best, - Scott

**Comment by ScottyProw** [comment]
Hi, Erik -

I just activated my iPhone 8 running iOS11, and it says PasswdSafes isn't
supported.

I haven't reset my old iPhone 6 yet, so I still have access to the password
info - thank God!

But I plan on sending it back to the company Gazelle.com for cash.

Is there a way to export all my password data?

Thanks for writing back.

All the best, - Scott

**Comment by erikjjohnson** [comment]
Hi

You can get your passwords by first getting them off your phone and then opening them in any other password safe program 

To get the passwords off your phone either:

Connect your phone to your computer. Open iTunes and under your apps in iTunes find passwordsafes. Then under password safes go to documents and drag and drops the pwsafe3 files from iTunes to your computer

To read the passwords from your computer you can search for password safe and download any of a number of apps that read the same format as this app does

**Comment by ScottyProw** [comment]
Thanks, Erik - I managed to figure it out.

But I really appreciate you answering me.

Have a good one!

Scott
